### ISSUE TITLE
Abandoned¿?

### ISSUE THREAD

**Issue by kidandcat** [thomasbachem/php-ga#24]
Last commit is from November 2015, there are 8 pull requests open. Has the library been abandoned?

**Comment by fzoccara** [comment]
As wrote in README:

NOTE: php-ga is no longer maintained as Google finally released an official server-side tracking API: Measurement Protocol! I couldn't find any well-implemented client library for PHP yet, so feel free to help make php-ga 2.0 a Measurement Protocol PHP client library.
